// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqL0gwsrjisSlE6WQx2f4IQFj_WT9-Qc',
    appId: '1:16245552672:web:4c19b933d989ffb493ae45',
    messagingSenderId: '16245552672',
    projectId: 'styleslate-a5cb4',
    authDomain: 'styleslate-a5cb4.firebaseapp.com',
    storageBucket: 'styleslate-a5cb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkj_VcnMejbZFgrUhAM9TKzYNflO7dy84',
    appId: '1:16245552672:android:af7926f09f9a9d7193ae45',
    messagingSenderId: '16245552672',
    projectId: 'styleslate-a5cb4',
    storageBucket: 'styleslate-a5cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAijZhhjPBEBx5RmmjSxdswqgTGk3d39U',
    appId: '1:16245552672:ios:6910699ea410c81293ae45',
    messagingSenderId: '16245552672',
    projectId: 'styleslate-a5cb4',
    storageBucket: 'styleslate-a5cb4.appspot.com',
    iosBundleId: 'com.example.hamroBarberMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAijZhhjPBEBx5RmmjSxdswqgTGk3d39U',
    appId: '1:16245552672:ios:6910699ea410c81293ae45',
    messagingSenderId: '16245552672',
    projectId: 'styleslate-a5cb4',
    storageBucket: 'styleslate-a5cb4.appspot.com',
    iosBundleId: 'com.example.hamroBarberMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRqL0gwsrjisSlE6WQx2f4IQFj_WT9-Qc',
    appId: '1:16245552672:web:1c60c0f10bb5f8b093ae45',
    messagingSenderId: '16245552672',
    projectId: 'styleslate-a5cb4',
    authDomain: 'styleslate-a5cb4.firebaseapp.com',
    storageBucket: 'styleslate-a5cb4.appspot.com',
  );
}
