import 'package:flutter/material.dart';
import 'package:hamro_barber_mobile/theme/app_theme.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

// Generated by `dart run build_runner build` from every @widgetbook.UseCase
// annotation found under lib/. Re-run that command after adding, renaming,
// or deleting a use case.
import 'main.directories.g.dart';

void main() => runApp(const WidgetbookApp());

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        // Renders every use case inside the real app's own dark theme
        // instead of Widgetbook's default, so components look exactly
        // like they do in the app.
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(name: 'Hamro Barber Dark', data: AppTheme.dark()),
          ],
        ),
        // Preview each use case at a few common device sizes.
        ViewportAddon(Viewports.all),
      ],
    );
  }
}
